- name: Install NGINX and configure
  hosts: nginx
  become: true
  tasks:
    - name: apt update and upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Change default html file
      copy:
        src: index.html
        dest: /var/www/html/
    - name: Replace default page with custom index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
- name: Deploy app from GitHub
  hosts: nginx
  become: true
  tasks:
    - name: Clone the repository
      git:
        repo: https://github.com/sabreensalama/dockerize-node-app-task
        dest: /app
    - name: Install Node.js and npm
      apt:
        name: [nodejs , npm]
        state: present
        update_cache: true
    - name: Run the Node.js app
      shell: node /app/server.js &
   